config/routes.rb
Quantumpractice::Application.routes.draw do
  devise_for :users
  devise_for :users do 
    get '/users/sign_out' => 'devise/sessions#destroy' 
  end
  resources :movies
  get "home/index"

  match "/findmovie"=>"movies#find_movie"

  
  match "/projects"=>"home#projects"

  root :to => 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :cast, :desc, :genre, :name, :other_information, :poster, :rating, :reviews, :similar_movies, :trailer, :tweets
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_filter :authenticate_user!, :except=>[:index]
  def index
  end
  def projects
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  before_filter :authenticate_user!, :except=>[:index]
  def index
    
  end

  def find_movie
   @movie = RottenMovie.find(:title => params[:title], :expand_results => true, :limit => 1)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

	def find_movie_by_type(type)
		 @movies = RottenList.find(:type => type).first(15)
		 return @movies
	end


	def trailer
       i= 0 
       video =  HTTParty.get("#{@movie.links.clips}?apikey=46ahrg93dj6aqf8g7vt7yaaa") 
       video["clips"].each do |item| 
          if i<1 
            @trailer = item["links"]["alternate"] 
          end 
          i=i+1 
       end 
       return @trailer
	end

	def similar_movies
       
        response =  HTTParty.get("#{@movie.links.similar}?apikey=46ahrg93dj6aqf8g7vt7yaaa") 

         @similar_movies = response["movies"]
         return @similar_movies
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="en">

<head>
  <%= csrf_meta_tags %>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">

    <title>QUANTIUM MOVIE CHALLANGE</title>

    <meta name="keywords" content="Ruby,Ruby on Rails,Ruby freelancer,Rails Freelancer,Rails outsourcing company,Ruby outsourcing company">

    <meta name="author" content="Rails Galaxy Hari Krishna">
    <meta name="copyright" content="© Copyright 2013 Rails Galaxy">

    <meta http-equiv="content-language" content="EN">
    <meta http-equiv="Content-Type" content="text/html; iso-8859-1">


    <!-- styles -->
    <%= stylesheet_link_tag "bootstrap" %>
    <%= stylesheet_link_tag "bootstrap-responsive" %>
    <%= stylesheet_link_tag "fonts" %>

    <style>
    body {
      padding-top: 90px;
    }
    </style>

    <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!--fav and touch icons -->
  
</head>

<body cz-shortcut-listen="true">
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">

     
    <a class="brand login" href="<%= root_path %>" style="margin-top: 15px;">
     <span style="color: #febf26;font-size: 25px;padding-left: 55px;">QUANTIUM </span><br/>
     <span style="color: white;font-size: 25px;">MOVIE CHALLENGE</span>
    </a>
      <div class="nav-collapse">

        <ul class="nav">
        
          <li ><a href="<%= root_path %>">Home</a></li>
                   
        </ul>
      </div>
      <!--/.nav-collapse --> 
    </div>
  </div>
</div>

<div id="user_nav" style="margin-top: 15px;">
<table style="width: 100%;">
  <tr>
    <td>
        <% if user_signed_in? %>
        Welcome <b><%= current_user.email %> !</b>.
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete,:class=>"btn btn-warning btn-small" %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path,:class=>"btn btn-warning btn-large"%> or <%= link_to "sign in", new_user_session_path,:class=>"btn btn-warning btn-large" %>
      <% end %>
    </td>
    <td style="text-align: right;">
      <%= form_tag findmovie_path, :method => 'get',:style=>"margin: 0;" do %>
  
        <%= text_field_tag :title, params[:title],:placeholder => 'Search your favourite movies'%>
        <%= submit_tag "Search", :name => nil,:class=>"btn btn-warning btn-small" %>
    
      <% end %>
    </td>
  </tr>
</table>
  




</div>
<%= yield %>

<div class="footer">
  <div class="container">

     <h4>Developed by Hari Krishna</h4>
      <div class="span9"></div>
    </div>
  </div>
</div>

<!-- /container --> 
<!-- javascript --> 
 <%= javascript_include_tag "jquery" %>
 <%= javascript_include_tag "ga" %>
  

 <%= javascript_include_tag "bootstrap-transition" %>

 <%= javascript_include_tag "bootstrap-tooltip" %>

 <%= javascript_include_tag "bootstrap-popover" %>
 <%= javascript_include_tag "bootstrap-button" %>
 <%= javascript_include_tag "bootstrap-collapse" %>
 <%= javascript_include_tag "bootstrap-carousel" %>

 <%= javascript_include_tag "bootstrap-typeahead" %>
 <%= javascript_include_tag "bootstrap-typeahead" %>
 <%= javascript_include_tag "feature_carousel" %>

 <%= javascript_include_tag "common" %>
 
 <%= javascript_include_tag "jquery.min" %>
<%= javascript_include_tag "highcharts" %>



<script type="text/javascript">
$(document).ready(function(){
  slider();

});
</script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34335433-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();


// $('.notClicked').click(function()
// {
//  alert("clicked");
//  $(this).removeClass('notClicked');
//     $(this).addClass('active');
//     alert(window.location.pathname);
// });

</script>

<script type="text/javascript" charset="utf-8">

$(window).load(function () {
 
  jQuery('.nav li').each(function() {
   
    var href = jQuery(this).find('a').attr('href');
    if (href === window.location.pathname) {
      jQuery(this).addClass('active');
    }
  });
});

</script>


</body>

app/views/movies/_form.html.erb
<div class="container" style="margin-top: 2%;margin-bottom: 2%;">
    <div class="row">
      <div class="span8" style="background-color: #f1f1f1;border-radius: 12px;text-align: center;">
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br/><br/><br/>
 <table>
   <tr>
     <td style="width: 60%;"><%= f.label :name %></td>
     <td> <%= f.text_field :name %></td>
   </tr>
   <tr>
     <td> <%= f.label :poster %></td>
     <td> <%= f.text_field :poster %></td>
   </tr>
   <tr>
     <td>
  
    <%= f.label :desc %>
   
  </td>
     <td> <%= f.text_field :desc %></td>
   </tr>
   <tr>
     <td>
    <%= f.label :rating %>
    </td>
     <td><%= f.text_field :rating %>
  
    </td>
   </tr>
   <tr>
     <td><%= f.label :genre %>
    </td>
     <td><%= f.text_field :genre %>
  
    </td>
   </tr>
   <tr>
     <td><%= f.label :cast %>
    </td>
     <td><%= f.text_field :cast %>
  </td>
   </tr>
   <tr>
     <td>
    <%= f.label :trailer %>
    </td>
     <td><%= f.text_field :trailer %>
  </td>
   </tr>
   <tr>
     <td>
    <%= f.label :reviews %>
    </td>
     <td><%= f.text_field :reviews %>
  
    </td>
   </tr>
   <tr>
     <td><%= f.label :tweets %>
    </td>
     <td><%= f.text_field :tweets %>
 
    </td>
   </tr>
   <tr>
     <td><%= f.label :similar_movies %>
   </td>
     <td> <%= f.text_area :similar_movies,:size=>"30X30" %>
  
    </td>
   </tr>
   <tr>
     <td><%= f.label :other_information %>
    </td>
     <td><%= f.text_area :other_information,:size=>"30X30" %>
  
    </td>
   </tr>
   <tr><td><%= f.submit %></td></tr>
 </table>
    
 
<% end %>

</div>
</div>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/find_movie.html.erb
<% if @movie.empty? %>
<div class="container" style="margin-top: 2%;margin-bottom: 2%;">
    <div class="row">

      <div class="span12" style="background-color: #f1f1f1;border-radius: 12px;">
          <h4 style="padding: 5%;text-align: center;">No movies found </h4>
      </div>
    </div>
          </div>
<% else %>


<div class="container" style="margin-top: 2%;margin-bottom: 2%;">
    <div class="row">

      <div class="span12" style="background-color: #f1f1f1;border-radius: 12px;">
      </br><span style="font-size: 25px;color: black;margin-left: 43%;"><%= @movie.title.upcase %></span></br></br>
          <div class="span5" style="background-color: #f1f1f1;border-radius: 12px;">

          <table>
          	<tr>
          		<td style="width: 150px;"><b>TITLE</b></td>
          		<td><%= @movie.title %></td>
          	</tr>
            <tr style="height: 20px;"><td></td><td></td></tr> 
          	<tr>
          		<td><b>CAST</b></td>
          		<td>
          		   <% @movie.abridged_cast.each do |cast| %>
						<ul>
              <li> <%= cast.name %></br></li>
            </ul>
           
					<% end %>
			    </td>
          	</tr>
            <tr style="height: 20px;"><td></td><td></td></tr>
          	<tr>
          		<td><b>Critic Rating</b></td>
          		<td><%= @movie.ratings.critics_rating %></td>
          	</tr>

            <tr style="height: 20px;"><td></td><td></td></tr>

          	<tr>
          		<td><b>Critic Score</b> </td>
          		<td><%= @movie.ratings.critics_score %></td>
          	</tr>

            <tr style="height: 20px;"><td></td><td></td></tr>


          	<tr>
          		<td><b>Audience Rating</b></td>
          		<td><%= @movie.ratings.audience_rating %></td>
          	</tr>

            <tr style="height: 20px;"><td></td><td></td></tr>


          	<tr>
          		<td><b>Audience Score</b></td>
          		<td><%= @movie.ratings.audience_score %></td>
          	</tr>

            <tr style="height: 20px;"><td></td><td></td></tr>

            <tr>
              <td><b>Trailer</b></td>
              <td><a href="<%= trailer %>" target="_blank">Click here to view trailer</a></td>
            </tr>

            <tr style="height: 20px;"><td></td><td></td></tr>


            <tr>
              <td><b>Sinopsis</b></td>
              <td style="text-align: justify;"><%= @movie.synopsis %></td>
            </tr>

            <tr style="height: 20px;"><td></td><td></td></tr>

            <tr>
              <td><b>Similar Movies</b></td>
              <td><% similar_movies.each do |movie| %>
                    <ul><li><%=link_to movie["title"],findmovie_path(:title=>movie["title"]) %></li></ul>
                   <% end %>
                   <% if similar_movies.nil? %>
                    No Similar kind of movies 
                   <% end %>
              </td>
            </tr>
            <tr style="height: 20px;"><td></td><td></td></tr>
          </table>
			 



			

			
		</div>

		<div class="span5" style="background-color: #f1f1f1;border-radius: 12px;text-align: center;">
			<%= image_tag @movie.posters.original,:style=>"width: 400px;height: 500px;" %>
			<br/><br/><br/><br/><br/><br/>


			
		</div>
    

    </div>
    </div>

        </div>
    </div>
</div>
<% end %>

app/views/movies/index.html.erb
<div class="container" style="margin-top: 2%;margin-bottom: 2%;">
    <div class="row">
      <div class="span12" style="background-color: #f1f1f1;border-radius: 12px;text-align: center;">
	     <% @in_theaters = find_movie_by_type("in_theaters") %>
	      <br/><h2>Movies In Theaters</h2><br/>
	    
	      <% count = 1 %>
	      <% @in_theaters.each do |movie| %>
				
			<%= link_to(image_tag(movie.posters.profile,:style=>"width: 200px;height: 200px;",:title => movie.title, :mouseover => movie.posters.profile), findmovie_path(:title=>movie.title)) %>&nbsp&nbsp&nbsp&nbsp
			<% if count%5==0 %><br/><br/><% end %>
	         <% count +=1 %>
		  <% end %>
		  <br/>
	    </div>
    </div>
    <br/>
</div>




<div class="container" style="margin-top: 2%;margin-bottom: 2%;">
    <div class="row">
      <div class="span12" style="background-color: #f1f1f1;border-radius: 12px;text-align: center;">
	      <% @box_office = find_movie_by_type("box_office") %>
	      <br/><h2>Movies In Box Office</h2><br/>
	    
	      <% count = 1 %>
	      <% @box_office.each do |movie| %>
				
			<%= link_to(image_tag(movie.posters.profile,:style=>"width: 200px;height: 200px;"), findmovie_path(:title=>movie.title)) %>&nbsp&nbsp&nbsp&nbsp
			<% if count%5==0 %><br/><br/><% end %>
	         <% count +=1 %>
		  <% end %>
		  <br/>
	    </div>
    </div>
</div>



<div class="container" style="margin-top: 2%;margin-bottom: 2%;">
    <div class="row">
      <div class="span12" style="background-color: #f1f1f1;border-radius: 12px;text-align: center;">
	      <% @opening = find_movie_by_type("opening") %>
	      <br/><h2>Movies Opening</h2><br/>
	    
	      <% count = 1 %>
	      <% @opening.each do |movie| %>
				
			<%= link_to(image_tag(movie.posters.profile,:style=>"width: 200px;height: 200px;"), findmovie_path(:title=>movie.title)) %>&nbsp&nbsp&nbsp&nbsp
			<% if count%5==0 %><br/><br/><% end %>
	         <% count +=1 %>
		  <% end %>
		  <br/>
	    </div>
    </div>
</div>



<div class="container" style="margin-top: 2%;margin-bottom: 2%;">
    <div class="row">
      <div class="span12" style="background-color: #f1f1f1;border-radius: 12px;text-align: center;">
	      <% @upcoming = find_movie_by_type("upcoming") %>
	      <br/><h2>Movies Upcoming</h1><br/>
	    
	      <% count = 1 %>
	      <% @upcoming.each do |movie| %>
				
			<%= link_to(image_tag(movie.posters.profile,:style=>"width: 200px;height: 200px;"), findmovie_path(:title=>movie.title)) %>&nbsp&nbsp&nbsp&nbsp
			<% if count%5==0 %><br/><br/><% end %>
	         <% count +=1 %>
		  <% end %>
		  <br/>
	    </div>
    </div>
</div>


<br/><br/><br/>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @movie.name %>
</p>

<p>
  <b>Poster:</b>
  <%= @movie.poster %>
</p>

<p>
  <b>Desc:</b>
  <%= @movie.desc %>
</p>

<p>
  <b>Rating:</b>
  <%= @movie.rating %>
</p>

<p>
  <b>Genre:</b>
  <%= @movie.genre %>
</p>

<p>
  <b>Cast:</b>
  <%= @movie.cast %>
</p>

<p>
  <b>Trailer:</b>
  <%= @movie.trailer %>
</p>

<p>
  <b>Reviews:</b>
  <%= @movie.reviews %>
</p>

<p>
  <b>Tweets:</b>
  <%= @movie.tweets %>
</p>

<p>
  <b>Similar movies:</b>
  <%= @movie.similar_movies %>
</p>

<p>
  <b>Other information:</b>
  <%= @movie.other_information %>
</p>


<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>